// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1, arg2) {
  return window['go']['main']['App']['AddConnection'](arg1, arg2);
}

export function AddDevice(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddDevice'](arg1, arg2, arg3);
}

export function AddWatch(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddWatch'](arg1, arg2, arg3, arg4);
}

export function StartPolling() {
  return window['go']['main']['App']['StartPolling']();
}
