// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1, arg2) {
  return window['go']['main']['App']['AddConnection'](arg1, arg2);
}

export function AddDevice(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddDevice'](arg1, arg2, arg3);
}

export function AddRegisterDefinition(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddRegisterDefinition'](arg1, arg2, arg3, arg4, arg5);
}

export function AddRegisterGroup(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddRegisterGroup'](arg1, arg2, arg3);
}

export function GetDeviceConfig(arg1) {
  return window['go']['main']['App']['GetDeviceConfig'](arg1);
}

export function StartPolling() {
  return window['go']['main']['App']['StartPolling']();
}
