// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1:string,arg2:string):Promise<void>;

export function AddDevice(arg1:string,arg2:string,arg3:number):Promise<void>;

export function AddWatch(arg1:string,arg2:number,arg3:number,arg4:string):Promise<void>;

export function StartPolling():Promise<void>;
