// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {engine} from '../models';

export function AddConnection(arg1:string,arg2:string):Promise<void>;

export function AddDevice(arg1:string,arg2:string,arg3:number):Promise<void>;

export function AddRegisterDefinition(arg1:string,arg2:string,arg3:number,arg4:number,arg5:string):Promise<void>;

export function AddRegisterGroup(arg1:string,arg2:string,arg3:number):Promise<void>;

export function GetDeviceConfig(arg1:string):Promise<engine.Device>;

export function StartPolling():Promise<void>;
